"""empty message

Revision ID: 3cba44a8275f
Revises: 848a3d286869
Create Date: 2019-03-01 12:49:40.552581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cba44a8275f'
down_revision = '848a3d286869'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('author', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'author')
    # ### end Alembic commands ###
